export const BUFFER_DAYS = 3;
export const RESERVATION_LENGTH = 5; // Number of days allowed for reservation
export const EMAIL = "finaltouchco.info@gmail.com"; 
export const MINIMUM_ORDER = 50;
export const SEND_INVOICE_DAYS = 45; // Days before the date to send invoice
export const PAYMENT_DUE_DAYS = 30; // Days before the date to send deposit
export const BACKEND_URL = "https://finaltouchco-backend.onrender.com"
// export const BACKEND_URL = "http://192.168.0.46:8080"
// export const BACKEND_URL = "http://localhost:8080";